import typing

import gdb
from metal.gdb.metal_break import MetalBreakpoint

class ExitBreakpoint(gdb.Breakpoint, MetalBreakpoint):
    def __init__(self): ...
    def handle_exit_event(self, event: gdb.ExitedEvent): ...
    def stop(self) -> typing.Optional[bool]: ...

    def exit(self, exit_code: int) -> None: ...
    def connect_event(self)     -> None: ...
    def disconnect_event(self)  -> None: ...
    def __enter__(self)         -> None: ...
    def __exit__(self)          -> None: ...
