import gdb
import threading
import datetime
import time


class Timeout(gdb.Parameter):
    def __init__(self): ...

    def connect_events(self):    ...
    def disconnect_events(self): ...

    def __enter__(self): ...
    def __exit__(self): ...

    set_doc: str
    show_doc: str

    def get_set_string(self) -> str: ...
    def work(self, dummy: None):...
    def interrupt(self): ...

    def cont(self, ev: gdb.ContinueEvent): ...
    def stop(self, ev: gdb.StopEventEvent): ...
    def quit(self): ...

    def exit(self, ev: gdb.ExitedEvent) -> None : ...

